// ⚠ This file was generated by the markdown vite plugin.
			// Any manual modifications will be overwritten and lost.
			
			
/**
* See https://github.com/pngwn/MDsveX/blob/main/packages/mdsvex/globals.d.ts
*/
declare module '*.md' {
import type { SvelteComponent } from 'svelte';

export default SvelteComponent;
export const metadata: Record<string, unknown>;
}
declare module 'virtual:markdown' {
	interface Collections {}
}

		type Markdown<T extends Record<string,unknown> = Record<string,unknown>> = {
			default: SvelteComponent;
			metadata: T
		}

		declare module 'virtual:works' {
	import type { z } from 'zod/v4';
	import type { Collections } from 'virtual:markdown';

	type Metadata = Collections.works['schema'] extends ZodObject
		? z.infer<Collections.works['schema']>
		: Record<string, unknown>;

	export const slugs: readonly [];
	export type Slug = (typeof slugs)[number];
	export const all: (Markdown<Metadata> & { slug: Slug })[];
	export async function one(slug: Slug, locale?: Locale): Promise<Markdown<Metadata>>
}