/*
 * This type declaration is generated by the markdown preprocessor.
 * Do not modify it, it will be overwritten on next startup.
 */

declare module '*.md' {
	export default string;
	export const metadata: Record<string, unknown>;
}